/*
 * The Continuing Education Tracking System, "CETS," is a professional education
 * tracking application for state and federally licensed individuals who have to
 * complete and document their required continuing education credits ("CEU's")
 * in order to be eligible for periodic license renewal. The application allows
 * users to create their own account and document education courses with an
 * automated sum of hours completed for easy reference. If required by an audit,
 * or to fulfill workplace requirements, the app also support a completed
 * education summary report in a text file.
 */
package edu.regis.cs444continuingeducationtrackingsystem.presentation;

import cs444continuingeducationtrackingsystem.domain.*;
import cs444continuingeducationtrackingsystem.service.*;
import javax.swing.JOptionPane;

/**
 * Main entry point (class) of application. Users may login, navigate to create
 * a new account, or exit program.
 *
 * @author Nathan Thomas
 * @version 1.0
 */
public class LoginUI extends javax.swing.JFrame {
   
   static ProcessAccountsFileImpl fileImpl = new ProcessAccountsFileImpl();

   /**
    * Creates new form LoginUI
    */
   public LoginUI() {
      initComponents();
      fileImpl.processFile();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      loginHeadingLbl = new javax.swing.JLabel();
      loginLbl = new javax.swing.JLabel();
      usernameLbl = new javax.swing.JLabel();
      passwordLbl = new javax.swing.JLabel();
      usernameFld = new javax.swing.JTextField();
      passwordFld = new javax.swing.JPasswordField();
      loginBtn = new javax.swing.JButton();
      createAccountBtn = new javax.swing.JButton();
      quitBtn = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("CETS");
      setBackground(new java.awt.Color(204, 204, 204));
      setBounds(new java.awt.Rectangle(500, 300, 420, 300));
      setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      setIconImages(null);
      setMaximumSize(new java.awt.Dimension(435, 350));
      setMinimumSize(new java.awt.Dimension(435, 350));
      setName("LoginFrame"); // NOI18N
      setPreferredSize(new java.awt.Dimension(435, 350));
      setResizable(false);
      setSize(new java.awt.Dimension(450, 335));

      loginHeadingLbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      loginHeadingLbl.setText("Continuing Education Tracking System");

      loginLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
      loginLbl.setText("Login");

      usernameLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      usernameLbl.setText("Username");

      passwordLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      passwordLbl.setText("Password");

      usernameFld.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      usernameFld.setToolTipText("Username");
      usernameFld.setName("userNameFld"); // NOI18N
      usernameFld.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            usernameFldActionPerformed(evt);
         }
      });

      passwordFld.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      passwordFld.setToolTipText("password");

      loginBtn.setText("Login");
      loginBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      loginBtn.setMaximumSize(new java.awt.Dimension(122, 26));
      loginBtn.setMinimumSize(new java.awt.Dimension(122, 26));
      loginBtn.setPreferredSize(new java.awt.Dimension(122, 26));
      loginBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            loginBtnActionPerformed(evt);
         }
      });

      createAccountBtn.setText("Create Account");
      createAccountBtn.setAlignmentY(0.0F);
      createAccountBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            createAccountBtnActionPerformed(evt);
         }
      });

      quitBtn.setText("Quit");
      quitBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            quitBtnActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(layout.createSequentialGroup()
                  .addGap(70, 70, 70)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(usernameLbl)
                     .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(37, 37, 37)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(passwordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(usernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(loginLbl)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(47, 47, 47)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(loginHeadingLbl))))
            .addGap(0, 0, Short.MAX_VALUE))
         .addGroup(layout.createSequentialGroup()
            .addGap(145, 145, 145)
            .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(155, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(loginHeadingLbl)
            .addGap(1, 1, 1)
            .addComponent(loginLbl)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(usernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(usernameLbl))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(passwordLbl)
               .addComponent(passwordFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(createAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(84, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void usernameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_usernameFldActionPerformed

   private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
      this.setVisible(false);
      CreateAccountUI createAccountUI = new CreateAccountUI();
      createAccountUI.setVisible(true);
   }//GEN-LAST:event_createAccountBtnActionPerformed

   private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
      Login login = new Login();
      login.setUsername(usernameFld.getText());
      login.setPassword(new String(passwordFld.getPassword()));

      if (!login.validate()) {
         JOptionPane.showMessageDialog(this, "Valid Username and Password"
                 + " Required", "Error", JOptionPane.ERROR_MESSAGE);
         return;
      }

      IAccountSvc impl = AccountSvcCacheImpl.getInstance();
      Account account = impl.authenticate(login);

      if (account == null) {
         JOptionPane.showMessageDialog(this, "Username/Password not "
                 + "valid. Create an account or try again", "Error",
                 JOptionPane.ERROR_MESSAGE);
         return;
      } else {
         this.setVisible(false);
         MainUI mainUI = new MainUI();
         mainUI.setAccount(account);
         mainUI.setVisible(true);
      }
   }//GEN-LAST:event_loginBtnActionPerformed

   private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
      System.exit(0);
   }//GEN-LAST:event_quitBtnActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new LoginUI().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton createAccountBtn;
   private javax.swing.JButton loginBtn;
   private javax.swing.JLabel loginHeadingLbl;
   private javax.swing.JLabel loginLbl;
   private javax.swing.JPasswordField passwordFld;
   private javax.swing.JLabel passwordLbl;
   private javax.swing.JButton quitBtn;
   private javax.swing.JTextField usernameFld;
   private javax.swing.JLabel usernameLbl;
   // End of variables declaration//GEN-END:variables
}
